name: Digpan
favicon: null
layout_spectrum: 0.74388
typography_spectrum: 0.49409
title: Digital Plus Analog
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcf8f9'
    - '#000606'
    - '#617881'
    - '#b8c6cf'
    - '#979fa2'
  brandStrength: 0.06561013194732368
  lightness: 0.8474425435997546
  saturation: 0.02980449120514095
  rhythmicContrast: 0.6640060083009303
purpose: []
