name: Digpan
favicon: null
layout_spectrum: 0.75422
typography_spectrum: 0.8222726390231401
title: Digital Plus Analog
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.06561013194732368
  lightness: 0.8474425435997546
  saturation: 0.02980449120514095
  rhythmicContrast: 0.6640060083009303
purpose: []
